name: investify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2

flutter:
  uses-material-design: true
