name: investify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  flutter_xlider: ^3.5.0
  fl_chart: ^0.69.2
  talker_flutter: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_bloc_logger: ^4.5.2
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.2.1
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  animated_custom_dropdown: ^3.1.1



dependency_overrides:
  analyzer: ^6.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner:
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icons/investify_icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/app_icons/
    - .env
